### ISSUE TITLE
Update async-icq to ibc-go/v8

### ISSUE THREAD

**Issue by Taztingo** [cosmos/ibc-apps#150]
We are in the process of updating Provenance Blockchain to cosmos sdk v0.50.0, and one step involves updating ibc-go to v8. One of our dependencies is async-icq, and unfortunately it doesn't have support for ibc-go/v8 yet. A new tagged version of async-icq/v8 would be very helpful.

**Comment by Reecepbcups** [comment]
ref: #157 as well
