### ISSUE TITLE
test: PFM test case for CI job `ictest-forward` is failing on main

### ISSUE THREAD

**Issue by jtieri** [cosmos/ibc-apps#162]
After the upgrades to the PFM to accommodate ibc-go v8 we are seeing one of the test cases fail in CI

see: https://github.com/cosmos/ibc-apps/actions/runs/7454152262/job/20284768753?pr=158

**Comment by Reecepbcups** [comment]
this may just be flakey. re-runnint - github did some networking changes recently and have seen more fail because of failed starts

**Comment by jtieri** [comment]
> this may just be flakey. re-runnint - github did some networking changes recently and have seen more fail because of failed starts

that was my initial thought as well but i re-ran it a few times between last night and today and it kept failing in the same way so figured i would at least open an issue so we can verify tests are passing locally. it looked like they were passing in the initial PR so perhaps it is just a GitHub runner issue causing weirdness

**Comment by Reecepbcups** [comment]
re-run passed: https://github.com/cosmos/ibc-apps/actions/runs/7454152262/job/20318173217
