### ISSUE TITLE
Remove gogoproto replace statements for v8

### ISSUE THREAD

**Issue by Taztingo** [cosmos/ibc-apps#167]
I'm currently assisting the Provenance Blockchain in migrating to sdk 50. One step in this migration process is the ability to remove `github.com/gogo/protobuf => github.com/regen-network/protobuf v1.3.3-alpha.regen.1` from go.mod since cosmos/gogoproto is being used. The Provenance Blockchain cannot remove this dependency because it was not removed from async-icq/v8. This ibc-app should be able to remove it since it is no longer needed.

**Comment by Taztingo** [comment]
Official documentation can be found [here](https://github.com/cosmos/cosmos-sdk/blob/v0.47.6/UPGRADING.md#protobuf)

> This means you should replace all imports of github.com/gogo/protobuf to github.com/cosmos/gogoproto. This allows you to remove the replace directive replace github.com/gogo/protobuf => github.com/regen-network/protobuf v1.3.3-alpha.regen.1 from your go.mod file.

**Comment by Reecepbcups** [comment]
Making note: I need to check PFM too

**Comment by Reecepbcups** [comment]
we're good
