### ISSUE TITLE
add broken link check CI

### ISSUE THREAD

**Issue by Reecepbcups** [cosmos/ibc-apps#178]
ref: #176
https://github.com/tcort/markdown-link-check on every push?

**Comment by rootulp** [comment]
We run it on every PR in celestia-app (see this [workflow](https://github.com/celestiaorg/celestia-app/blob/e3e11e28ac5fbcc49563cfd633317ddf55617c70/.github/workflows/markdown-linter.yml#L25-L35)). Warning: it can be flaky sometimes so we don't enforce it as a required check prior to PR merge.

**Comment by Reecepbcups** [comment]
@rootulp Thank you! This was useful. The only flakey link I found is twitter/x, they probably do some weird blocking or redirect thing. oh well.

really helped clean up the codebase, so many broken
