### ISSUE TITLE
chore: remove `IBCMiddleware.refundTimeout` as it is no longer used

### ISSUE THREAD

**Issue by ysv** [cosmos/ibc-apps#189]
I was trying to understand meaning of refundTimeout inside IBCMiddleware but didn't find any usage of this attribute except initialization (3 times) and unit test (2 times) - see screenshot.

I'm still wondering what is the reason behind and if it should be present at all.

<img width="1496" alt="Screenshot 2024-05-01 at 17 47 15" src="https://github.com/cosmos/ibc-apps/assets/19859122/dda5987c-df93-453c-856a-a9a006fe4844">

**Comment by Reecepbcups** [comment]
cc @jtieri since you did a bit of refund work iirc due to Mandrake

**Comment by agouin** [comment]
This parameter is no longer used after the introduction of atomic acks. It can be safely ignored (set to arbitrary value) and should be removed in a future release
