### ISSUE TITLE
`NFT Transfer (ICS 721)` should be imported to https://github.com/cosmos/ibc-apps/blob/main/modules/ 

### ISSUE THREAD

**Issue by jonathanpberger** [cosmos/ibc-apps#22]
- [ ] put the softwhere where it oughtta be
- [ ] update the `List of Apps` / `Ecosystem Apps` tables in the README.

**Comment by Reecepbcups** [comment]
from stargaze

**Comment by agouin** [comment]
https://github.com/public-awesome/cw-ics721

**Comment by Reecepbcups** [comment]
@agouin this may actually be referencing https://github.com/bianjieai/nft-transfer ? (as this is an actual module and not a CW impl)

We link to both in the README already, but seems `nft-transfer` is closed to what we would want here for now?

**Comment by akc2267** [comment]
NFT transfers are discoverable from the ibc-apps repo. getting this fully imported would require bianjie team to be added to cosmos org and for them to archive their own repos. closing as wont fix for now
