### ISSUE TITLE
Integrate CI tests for apps and middleware

### ISSUE THREAD

**Issue by boojamya** [cosmos/ibc-apps#28]
There should be CI testing for each application and module.

We should document and standardize this process and make is smooth for future incoming apps.

Some R and D may be necessary for mono repos like this.

**Comment by akc2267** [comment]
writing tests for PFM - still need simapp

**Comment by akc2267** [comment]
CI tests should also work for example code (PFM and ICQ need example code)

**Comment by Reecepbcups** [comment]
The CI should only run for the modules which have changes using github CI conditionals

**Comment by Reecepbcups** [comment]
We are also going to handle for the Osmosis team using my Juno ref: https://github.com/CosmosContracts/juno/blob/main/interchaintest/module_ibchooks_test.go

then we can make a PR for the osmosis team to use

**Comment by Reecepbcups** [comment]
Completed for PFM & AsyncICQ
