### ISSUE TITLE
PFM hook possible fixes when used along with IBC-hook? #

### ISSUE THREAD

**Issue by dzmitry-lahoda** [cosmos/ibc-apps#68]
Hello, what is planned fix for https://github.com/SCV-Security/responsible-disclosures/blob/main/SCV%20-%20Responsible%20Disclosure%20-%20PFM%20and%20IBC-hooks.pdf ?
I though of all fixes I can do in contract with all data available, the only fix CW developer can do is signed token inside packet, but without ZK this is dead end for IBCing high gas cost chains with different signature schemes.
Planned fix would help to write code the way anticipating that fix to happen.
Thank you

**Comment by akc2267** [comment]
PR to address this issue: #71
