### ISSUE TITLE
add mergify to CI 

### ISSUE THREAD

**Issue by jtieri** [cosmos/ibc-apps#7]
We should add mergify to the repo to assist in back porting issues across supported branches/releases. It has been a huge help in other repos and I can see it being especially useful here as well

**Comment by jonathanpberger** [comment]
@jtieri is adding some version of PFM; once done, this'll be unblocked and @boojamya will add to mergify.

**Comment by jonathanpberger** [comment]
ongoing discussion about branch naming (which will impact how we backport).

One brand/version of `ibc-go` that we're maintaining
