### ISSUE TITLE
Migrate away from deprecated x/params module

### ISSUE THREAD

**Issue by Reecepbcups** [cosmos/ibc-apps#87]
### Affected applications:
- [x] [Packet Forward Middleware](https://github.com/cosmos/ibc-apps/blob/main/middleware/packet-forward-middleware/router/keeper/params.go)
- [ ] [Async-ICQ](https://github.com/cosmos/ibc-apps/blob/main/modules/async-icq/keeper/params.go)

### Reason:
SDK v46 deprecated this module, and it is being removed in SDK 48/50.

### Solution
Migrate from the x/params module to being saved within the keeper

**Comment by akc2267** [comment]
only needs to be done once sdk 50 goes live

**Comment by akc2267** [comment]
need to get this supported for v47, because params in v46 is being deprecated
